### ISSUE TITLE
rav-lookup:  segment fault 

### ISSUE THREAD

**Issue by calanor** [tschiemer/aes67#1]
Segment Fault executing rav-lookup (also in other utilities)  located in src/utils/mdns-avahi.c line 352 when address is NULL.  
It always happens with a particular mdns packet.  I do not know in which cases address can be 0.

**Comment by tschiemer** [comment]
Hi!

thanks for the issue.

I'd imagine it to be NULL when there was a resolver failure event as opposed to a resolver found event (switch statement right before).
I assume the following re-ordering and additional safeguard might resolve the problem, and I further assume that you should see a proper error message (I think) - would you mind checking?

`

    char * txtstr = NULL;
    uint16_t txtlen = 0;
    enum aes67_net_ipver ipver = aes67_net_ipver_undefined;
    const uint8_t * ip = NULL;

    enum aes67_mdns_result result = aes67_mdns_result_error;

    /* Called whenever a service has been resolved successfully or timed out */
    switch (event) {
        case AVAHI_RESOLVER_FAILURE:
    //            fprintf(stderr, "(Resolver) Failed to resolve service '%s' of type '%s' in domain '%s': %s\n", name, type, domain, avahi_strerror(avahi_client_errno(avahi_service_resolver_get_client(r))));
            result = aes67_mdns_result_error;
            break;

        case AVAHI_RESOLVER_FOUND: {
    //            fprintf(stderr, "Service '%s' of type '%s' in domain '%s':\n", name, type, domain);
            if (res->type == restype_resolve2){
                result = res->result;
            } else {
                result = aes67_mdns_result_discovered;
            }
            txtstr = avahi_string_list_to_raw(txt, &txtlen);

            if (address && address->proto == AVAHI_PROTO_INET){
                ipver = aes67_net_ipver_4;
                ip = (uint8_t*)&address->data.ipv4.address;
            } else if (address && address->proto == AVAHI_PROTO_INET6){
                ipver = aes67_net_ipver_6;
                ip = address->data.ipv6.address;
            }
            break;
        }
    }


`

If this does not resolve the problem, as you're saying it occurs with a particular mdns packet, could you share the raw packet maybe (or a traffic log for that matter, can send me by email to philip.tschiemer at that gmail.com )?

Out of interest, which device(s) are you using the utility with?

**Comment by calanor** [comment]
The same with this patch.  Segmentation fault (core dumped) when receive this packet.
I send a capture to your email.

Thanks,

**Comment by calanor** [comment]
Sorry. 
with your patch there is no  Segmentation fault occur.  
I had not deleted some code that you have moved inside the switch. A git diff is better in these cases.

**Comment by tschiemer** [comment]
Sorry for being unclear but happy to hear that this resolves the issue.
