### ISSUE TITLE
sdp not valid if have one space after v=0

### ISSUE THREAD

**Issue by calanor** [tschiemer/aes67#2]
Some of my machines put a space after v=0 
`v=0 \n`
but aes67_sdp_fromstr function return an AES67_SDP_ERROR.

It is due to sdp.c line 1395 and I do not see in RFC4556 anything that prohibits one or more spaces between v=0 and CR/LF
In other sdp lines this error does not occur.

**Comment by tschiemer** [comment]
Hi, thanks for the issue.

Indeed, it's rather strict at the start of the description. That's how I'd understand the RFC, even it is not explicit (also see excerpt below) and any SDPs I've encountered so far.

Actually it seems rather strange in my eyes to add a space for no reason (especially at the fixed header) unless the tools used to generate the SDP were (generally) constructed this way (like when using array/list functions of a scripting language).. out of curiosity, may I inquire as to what tool/component is generating these SDPs?

But in support of wider compatability the proposed change seems sensible. I'll try to get to it any of these days.

```txt

   An SDP session description consists of a number of lines of text of
   the form:

      <type>=<value>

   where <type> MUST be exactly one case-significant character and
   <value> is structured text whose format depends on <type>.  In
   general, <value> is either a number of fields delimited by a single
   space character or a free format string, and is case-significant
   unless a specific field defines otherwise.  Whitespace MUST NOT be
   used on either side of the "=" sign.
```

ie
```txt
<line> := <type> "=" <value>
<value> := <free-format-string> | <field> {" " <field>}
```

**Comment by calanor** [comment]
In this case, I think it is a VMIX that generates the space after v=0.

**Comment by tschiemer** [comment]
arbitrary number of spaces are now accepted after v=0 since [last commit](https://github.com/tschiemer/aes67/commit/9555aa7a183b422100322f5cc8017faabcf45d4e)

**Comment by calanor** [comment]
The patch work perfect.
The space in sdp after v=0 is generated by Merging RAVENNA ASIO Driver.
